id: PA0C4B2C3
initial_creation_type: input
source_metadata:
  title: Śikṣāsamuccaya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Mirek Rozehnahl
  contribution to GRETIL: Mirek Rozehnahl
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:22:56.557101'
last_modified_at: '2022-03-09T15:22:56.557184'
